/*
 * Payment Service API
 * API для проверки баланса и оформления заказа
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.payment.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetBalanceById200Response
 */
class GetBalanceById200ResponseTest {
    private final GetBalanceById200Response model = new GetBalanceById200Response();

    /**
     * Model tests for GetBalanceById200Response
     */
    @Test
    void testGetBalanceById200Response() {
        // TODO: test GetBalanceById200Response
    }

    /**
     * Test the property 'userId'
     */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'balance'
     */
    @Test
    void balanceTest() {
        // TODO: test balance
    }

}
