spring:
  application:
    name=yandex
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=true
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
  image:
    savePath: E:\\Yandex\\intershop\\storage
  servlet:
    multipart:
      file-size-threshold: 1048576
      max-file-size: 20848820
      max-request-size: 418018841
