/*
 * Payment Service API
 * API для проверки баланса и оформления заказа
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.payment.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CartPayment200Response
 */
@JsonPropertyOrder({
  CartPayment200Response.JSON_PROPERTY_STATUS,
  CartPayment200Response.JSON_PROPERTY_NEW_BALANCE
})
@JsonTypeName("cartPayment_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-18T22:36:48.959781700+04:00[Europe/Samara]", comments = "Generator version: 7.12.0")
public class CartPayment200Response {
  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_NEW_BALANCE = "newBalance";
  @jakarta.annotation.Nullable
  private Double newBalance;

  public CartPayment200Response() {
  }

  public CartPayment200Response status(@jakarta.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }

  public CartPayment200Response newBalance(@jakarta.annotation.Nullable Double newBalance) {
    
    this.newBalance = newBalance;
    return this;
  }

  /**
   * Get newBalance
   * @return newBalance
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEW_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getNewBalance() {
    return newBalance;
  }


  @JsonProperty(JSON_PROPERTY_NEW_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNewBalance(@jakarta.annotation.Nullable Double newBalance) {
    this.newBalance = newBalance;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CartPayment200Response cartPayment200Response = (CartPayment200Response) o;
    return Objects.equals(this.status, cartPayment200Response.status) &&
        Objects.equals(this.newBalance, cartPayment200Response.newBalance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, newBalance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CartPayment200Response {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    newBalance: ").append(toIndentedString(newBalance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

