server:
  port: 8081
spring:
  r2dbc:
  url: r2dbc:h2:mem:///paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE
  username: sa
  password:
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/master
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.web.authentication: DEBUG
jackson:
  serialization: WRITE_DATES_AS_TIMESTAMPS=false
