/*
 * Payment Service API
 * API для проверки баланса и оформления заказа
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.payment.client.api;

import ru.yandex.payment.client.model.CartPayment200Response;
import ru.yandex.payment.client.model.CartPayment400Response;
import ru.yandex.payment.client.model.CartPaymentRequest;
import ru.yandex.payment.client.model.GetBalanceById200Response;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Оплата заказа
     *
     * 
     */
    @Test
    public void cartPaymentTest()  {
        // uncomment below to test the function
        //CartPaymentRequest cartPaymentRequest = null;
        //CartPayment200Response response = api.cartPayment(cartPaymentRequest).block();

        // TODO: test validations
    }
    
    /**
     * Получение баланса
     *
     * 
     */
    @Test
    public void getBalanceByIdTest()  {
        // uncomment below to test the function
        //String userId = null;
        //GetBalanceById200Response response = api.getBalanceById(userId).block();

        // TODO: test validations
    }
    
}
