spring:
  application:
    name=yandex
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
  image:
    savePath: ${STORAGE_IMAGE_PATH:E:\Yandex\intershop\yandex\intershop\storage\images\}
  servlet:
    multipart:
      file-size-threshold: 1048576
      max-file-size: 20848820
      max-request-size: 418018841
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
payment-service-name: ${PAYMENT_SERVICE_NAME:localhost}
payment-service-port: ${PAYMENT_SERVICE_PORT:8081}